language: python
python:
    - "3.6.1"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python setup.py develop
  - cvemanager -d -p -csv
  - cvemanager -ps "" -db cve -cd
  - cvemanager -ps "" -db cve -ct
  - cvemanager -ps "" -db cve -idb -p
  - pytest -s < password.txt --cov=cvemanager tests/
