language: python
python:
    - "3.6.1"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - pytest -s < password.txt --cov=cvemanager tests/
